### ISSUE TITLE
update question

### ISSUE THREAD

**Issue by tomichen** [ameeno/Dell-E7440-Hackintosh#1]
Hello, I want to know if this release will be compatible with the new future version (for example, 10.14.3 or later). I really hope the author will continue to update this project for those hackintoshers (including me), 😊. Anyway, thanks for your sharing.

**Comment by ameeno** [comment]
Hello. I have updated the files and it works with the latest mojave.

I fully intend to keep it updated as this laptop is now my daily driver.

I wont commit to repo unless I have fully tested the configuration.

Also, it is recommended you set your own serial numbers using clover configurator. Enjoy.
