### ISSUE TITLE
WiFi Query

### ISSUE THREAD

**Issue by CraigHissett** [ameeno/Dell-E7440-Hackintosh#10]
Hi Ameeno

Fantastic work with this - I've followed your instructions and everything seems to work great except my WiFi.
I have scanned through the other raised issue regarding WiFi and was just wondering what steps you take in your setup to ensure your WifI card works in your setup?

I have a similar card to yours (mine is the DW1510) which reportedly should work out of the box, however it doesn't; it never finds any networks, and is described as 'not associated' in the status of the card.
If you can let me know how yours is configured maybe I could adjust mine to allow for the 1510 to work.

Many Thanks

Craig

**Comment by ameeno** [comment]
Hi Craig.

Fake Mac's are Very very sensitive to which cards they work with and which ones they won't. (Remember Apple makes very very few hardware variants in real Macs)

a "Similar" Card does not equal the same card so you cannot expect my wifi config to work on any *OTHER* card.

I do have experimental workings with a DW1820A on my ThinkPad T440P Repository, but even that is temperamental and sometimes does not work.

The only way to get wifi to work is to either get a FULLY supported card or perhaps google the exact texts/configs for the card in your possession and work out your config.!!!
My Recommended card for this laptop (half mini PCI is) 
https://wikidevi.com/wiki/AzureWave_AW-CE123H



Your choices:

You could buy a cheap TP-Link dongle if you don't mind it sticking out its like five USD (and max 150mbps)?

I have this one, and it works well but does require you to have downloaded and installed the driver previously:
https://www.amazon.co.uk/TP-LINK-TL-WN725N-Mbps-Wireless-N-Adapter/dp/B008IFXQFU/ref=sr_1_10?keywords=tplink+usb+wifi&qid=1560436139&s=gateway&sr=8-10

You could try if you are searching for Hackintosh solutions for your card, try searching for BCM4322 as that is the Broadcom chip in your card or simply "DW1510 Hackintosh" with Google, and read the forum posts.

However:
Not sure if it is worth trying to make an unsupported card work though pal. You can buy a 100% working one on eBay for a few bucks. Still far cheaper than a real MBPro! The easiest way is to buy the right card or live with ethernet only!

**Comment by ameeno** [comment]
**** EDIT This thread looks promising ****

https://www.hackintosh-forum.de/forum/thread/38980-dell-dw1510-wlan-will-nicht/

It is in German, but from what I can gather, the steps I describe below come into play here and seem to work.
Follow it and report back if works.
*** END OF EDIT**


Now, you have two types of cards with Hackintoshes, Ones that work OOB (Out of the box) and ones that can be spoofed to work, by tricking Apple into loading a driver for the card you have to make it work.

For the card I recommend, I use a kext called AppleBCRMfixup, which is inside the kext folder, and in the past, I have had to use fakepci_id to spoof the device ID.


Now in your case, perhaps just a device ID spoof is required? 


NOW, the difficulty you seem to have is: the card you mentioned used to work out of the box but does not seem to work with the latest Mojave install.

Which means perhaps you can use clover configurator to inject a fake PCI_ID into the boot configuration and load the two kexts from Rehabman 

here…
https://github.com/RehabMan/OS-X-Fake-PCI-ID

what you will most likely need is the fakepccid kext, the Broadcom injector kext and the correct pciid injected within clover.


The steps I follow to debug are usually I use registry explorer and look for the device id of my card (Broadcom status with 14e4 I think)
 and you can either A: hack the apple built in kexts to add your hardware ID, or b, Spoof your device id to force the driver to load.


It's very much a process of trial, error, backup reboot and try and modify it and test.

so if you find a forum post with direct instructions on how to use a particular piece of hardware, that is the easiest thing to do.

Unfortunately, as I do not have the card myself I can't give you specific instructions for your card, I can describe the process I follow to "try" and make an unsupported card work.

I hope this rambling brain dump helped you in some way.

I apologise if the instructions are not clear: you have to try lots of different things and hope it works with your tweaks!

Good luck, and report back if successful.

**Comment by CraigHissett** [comment]
Thank you so much for the advice matey; there's plenty for me to get stuck into there.
I had a feeling it could be something to do with kexts or injected setting matching your specific card or not. Ill try these out tonight.

**Comment by CraigHissett** [comment]
Hey, just a quick update - I removed all Wifi-related kexts and also a unticked the 'Fix Airport' in the ACPI section of Clover.
Restarted, and WiFi worked like a charm - I'm using it now!

Thank you for your help with this one matey, greatly appreciated!
