### ISSUE TITLE
3.5mm headset Very noisy. later, when i run(install.sh) it's mute

### ISSUE THREAD

**Issue by KaneGZ** [ameeno/Dell-E7440-Hackintosh#12]
At first it was very noisy, then I ran the Install.sh file. It has become dumb.
My English is very bad. please sympathize.

**Comment by KaneGZ** [comment]
The problem is solved when I choose to sleep, it darkens the screen and then lights up soon after. But when I restarted, it encountered that error. I have to sleep every time it restarts normally

**Comment by KaneGZ** [comment]
Another problem is that I can only use F3 to help reduce screen brightness. Other buttons do not work at all

**Comment by ameeno** [comment]
hello. you must use keys that is on real apple mac, this is hackintosh not real mac, keyboard mapping is like real apple not like dell.

thanks i close issue

**Comment by KaneGZ** [comment]
You can thoroughly fix the headset error

**Comment by ameeno** [comment]
Look at fixes folder. 


Please read the guides fullt
