### ISSUE TITLE
MacOS update query

### ISSUE THREAD

**Issue by CraigHissett** [ameeno/Dell-E7440-Hackintosh#13]
Just a quick question regarding updating the OS; I'm running Mojave and a new Mojave release is out now. Would installing this update risk screwing up the hackintosh setup or would it operate as expected?

Thanks

Craig

**Comment by ameeno** [comment]
updating is always a risk, if I where you I would mirror my root drive to a time machine or carbon copy cloner backup before updating.

saying that I always take the gamble and it has always worked fine for me.

YMMV.

by the way it is possible to move your "Home" directory to a seperate partition, just like you would under Linux. you could also move applications like the larger ones to another folder/drive/partition.

this way your entire root partition can be under 20gb, and compressed that would be a mere 3-5gb image.


these tips are not just incase of a failed upgrade. it is important to always make backups, especially when running something like a hackintosh as a primary machine.

**Comment by CraigHissett** [comment]
Thank you for the sound advice matey.
I'm looking to get an mSATA drive to go in the available slot to increase my storage space; once I've got that in for file storage I will look to partition my main drive as you recommend. At least then I can take the plunge with the upgrade and have a backup in case it goes wrong.

:)

**Comment by ameeno** [comment]
Once you go msata (and clone your boot partitions) just chuck in a slow high capacity HDD and throw your home folders onto that one, you could also make a time machine backup partition and also other partitions for Linux and windows. Your data will be safe and you won't get downtime.  for example mine  is (SSD) 200mb efi, 100gb Mac, 100gb win, 40ish GB Linux root. Also I use a 2 tb HDD with many different partitions for Mac Windows Linux and exfat (to share between os's)

(It's a Seagate Barracuda from Amazon for just £60) make sure it's 7mm.

 having something like a hackintosh may break so easily though a kext or update, so try and backup

**Comment by CraigHissett** [comment]
Tremendous, thanks man!
I've got a little NAS I've built handling the files I'll use cross
platform, so luckily I only need the partition for Mac only stuff :)
I'll be tracking a lot of audio so that switch to a high capacity drive
will be perfect.
Thanks again for your help buddy!
