### ISSUE TITLE
Question about UEFI and legacy

### ISSUE THREAD

**Issue by wtjin1992** [ameeno/Dell-E7440-Hackintosh#14]
Hi there! I followed you here from reddit. I am convinced by your successful hackintosh and thorough guide. So I've ordered a E7440 on ebay and expecting to receive it in a few days. I am now making the majave 10.14.5 installer and I'm wondering which boot mode should I follow in the guide, UEFI or legacy? Which one did you actually used in your own E7440? By the way, my model has a i7-4600U with HD4400 iGPU, 16gb ram, 256gb ssd. Thanks for your help!

**Comment by ameeno** [comment]
it needs to be UEFI pal.

the handy guide I have linked lets you make an installer from just windows (you know longer need a MacOS system available or a mac VMWare virtual machine image to make your initial Mac USB (Which is handy.
However, the truth is I DO NOT use my e7440 any more. It is sitting now on the floor at the side of my sofa in my front room and has not been turned on for weeks except to duplicate data.

My main Hackintosh laptop is now a heavily modified Thinkpad T440P.

The reasons are the T440P has a socketed CPU motherboard, and so I have a Quad core eight-thread processor (Which is handy for programming) and also can have up to 3 SSD/ Hard drives, and generally has a much nicer build and feel like a workhorse laptop.

Saying that the e7440 is a fantastic Hackintosh and I used it for over a year, full time at work as a development machine without problems and still maintain this boot pack to the best of my ability.

**Comment by ameeno** [comment]
Anyway, a few tips as a first-time setup:
If you already have windows installed on the machine and wish to maintain it:
use a Product key viewer tool to save the windows ten key before wiping it out.
https://www.nirsoft.net/utils/product_cd_key_viewer.html



Secondly, make sure you have an MSATA SSD drive inside your MSATA slot on the motherboard, this will free up the hard drive bay for a physical drive (More storage, Yay!!!)
I am not sure if your SSD will be a Msata or a SATA SSD, Hopefully, it is Msata and you can just MOVE it to the Msata Slot:
https://www.google.com/search?q=e7440+msata&client=firefox-b-d&channel=trow&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjAqd7i-JDjAhUNEcAKHU4PCW0Q_AUIESgC&biw=1536&bih=760&dpr=1.25#imgrc=FVpOkoAH39sFFM:



Thirdly, make sure you have the wifi Card I recommended the AW-CE123H, as its the only one I support, and it works very well in my experience



Finally, a 1080p Screen is kinda a MUST, in my opinion.




The steps I recommended for dual-booting are:
1) Make two INSTALL USB :macOS + Clover, & Win10 Installer USB.

2) Partitioning
After Booting from the MacOS/Clover USB. Use Apples Disk utility to erase the drive, and make a APPLE HSF (journaled Partition) And then Split this partition into two, to have two equal 50% of the drive apple partitions.


3) Installation:
Reboot and install windows 10 First, Selecting one of the previously created partitions Under Windows 10 custom install.

Once you have checked windows boots/Activates correctly, you can proceed to install MacOS Next.
 (into the NON-windows partition obviously)


This has been my most successful way of dual booting.
Good luck with your project & let me know how it goes!

**Comment by wtjin1992** [comment]
Thank you so much for your thorough explanation! I now have installed the hackinstosh on my E7440 and everything is working perfectly except that, I found that the cpu is stuck at 800mhz and there is nothing I can do to make it boost to higher frequencies. Do you have any idea what may have caused this issue? Any help will be appreciated! thanks in advance!

**Comment by wtjin1992** [comment]
Actually I found out that it is a problem of dell E7440 itself and has nothing to do with the hackintosh. I  solved this throttling problem following the guide here. https://www.youtube.com/watch?v=00xRSqyGnks&t=2s   It is a weird problem and seems to be very common in among dell e7440 machines. I tried many solutions out there and the above attached one finally helped me recover the boost frequency. Thank you again for your tutorial and I am quite satisfied with this hackintoshed machine right now!

**Comment by ameeno** [comment]
oh yea removing that pointless screw underneath the keyboard thing to stop pointless throttleing?

Thinking back i did that to my e7440 a long time ago when i was still using windows,

Must have slipped my mind, but glad you got it sorted.

I might make an adjustment to my readme linking your video to help other users!!!
glad it works for you.


Thanks for the reminder, I forgot about it.
