### ISSUE TITLE
Installing Error!

### ISSUE THREAD

**Issue by ibraheemqadir** [ameeno/Dell-E7440-Hackintosh#15]
It's saying 'The Recovery Server Could Not Be Contacted.' What should I do? I use the same laptop as mentioned in the guide.

**Comment by ameeno** [comment]
it must have an ethernet connection and you must have intelMausi kext in your kext/other directories

Your error sounds like the ethernet is not working and not able to connect to the apple download recovery server.

**Comment by ibraheemqadir** [comment]
Yeah I guessed so. Ethernet Net is not connected. How do we connect the Ethernet? And After Installing Hackintosh will the Built in Wifi Work? Also, can we use Time Machine Backup to Install Hackintosh?

**Comment by ameeno** [comment]
Yes if you have correct WiFi card it will work after install

**Comment by ameeno** [comment]
Ethernet is just needed for initial installation

**Comment by ameeno** [comment]
Yes it is like 99.9999% perfect Mac clone for the cost of £100 instead of £1500

**Comment by ibraheemqadir** [comment]
During the installation the mouse sensitivity as well as the track pad sensitivity is low. Will it be fixed after the installation. Also, do disk drives are being shown for installation.

**Comment by ameeno** [comment]
You can change trackpad sensitivity from settings and also the kext options. First step is install

**Comment by ibraheemqadir** [comment]
No Drives are being shown for installation

**Comment by ibraheemqadir** [comment]
Also Bro It would be great if you could create a YouTube video on it!

**Comment by ameeno** [comment]
Bro, I don't think you read the guide properly,

You must download my Full EFI Bootpack, and copy it to your USB efi folder after making the clover usb.

Thank you for the suggestion of a Youtube video, I will consider it. However, you can find other youtube videos on hackintosh boot process also :)
