### ISSUE TITLE
Format Error!

### ISSUE THREAD

**Issue by ibraheemqadir** [ameeno/Dell-E7440-Hackintosh#16]
I have formatted all my drives to macOS Journled and the disk controller is SATA but it's saying GMBR Partition not there so cant install. Plz help! Using same laptop as in the guide.

**Comment by ameeno** [comment]
please don't use the format option in disk utility, Use the "ERASE" option to erase the entire drive as macOSJournaled.

the erase option magically wipes the drive and creates a HIDDEN EFI partition(Approx 200mb), and a GPT partition table. It also creates a single Journaled partition for the remainder of the disk, First, do that and write to disk.

Return to install screen and see if the partition is selectable for install.


Finally, if you go into disk utility again, you will be able to modify the one large partition into several smaller partition (Add & delete partitions as you have been doing before).

that way you can customise your macOS installation partition and keep some space spare for other operating systems etc.

Good luck, You are getting closer to victory!

**Comment by ibraheemqadir** [comment]
Okay I'll do that. Does that mean by Bios configuration is correct. Also, is it possible to dual boot windows after installing Hackintosh

**Comment by ameeno** [comment]
yes if you do what I told you (Erase the full drive) and create EFI partition with apple journaled, then write to disk.

you can go BACK into disk utility and split the macos Journaled partition into TWO 
(the partition type of the second partition is not essential, but I usually use EXFAT so windows can see it)


And next, you can install windows onto the second partition after MacOS is installed.


Now there *OTHER WAYS* to do it, without wiping the full drive, 

but doing so requires far more knowledge about disk partitions than I believe you have.

However, if you google Convert windows to EFI/GPT for example, you may be able to convert your existing windows install to EFI/GPT.
Ex:
https://www.windowscentral.com/how-convert-mbr-disk-gpt-move-bios-uefi-windows-10


You Must boot as EFI/gpt using my guide as that is the only knowledge I have.
Seriously, my recommendation is you thoroughly read & FULLY grok the guides I have linked, All of them, every part.

Every question you have asked me is easily solved by reading all the guides.

Hope that helps & good luck.
