### ISSUE TITLE
Boot Problem!

### ISSUE THREAD

**Issue by ibraheemqadir** [ameeno/Dell-E7440-Hackintosh#17]
On start up it says Bootmgr is missing. When I boot tbe mac OS that I installed using the bootable USB Clover it shows a cross and does not boot at all!

**Comment by ibraheemqadir** [comment]
Okay I started it couple of time and noe mac is running but how to.add in bootlader

**Comment by ameeno** [comment]
As you are not reading the guide and have made 5 issues I have had to close. Which are not issues but just down to you not reading Instructions, 

I am blocking you from my repository.

Good luck.
