### ISSUE TITLE
unable to run this on a E7440 I7 4600U 

### ISSUE THREAD

**Issue by sikiro** [ameeno/Dell-E7440-Hackintosh#19]
i am getting a kextd stall at 240s IGPU and it just hanfs there unsure of what the issue is. i have tried with Mojave and high sierra i am using the correct hardware including a 3rd party compatible wifi card as you recommended and still same issue. any suggestions?

**Comment by ameeno** [comment]
Check the bios settings and verbose output. Try and do the I itial install without WiFi and ethernet only

**Comment by sikiro** [comment]
i will tr to do this now i will attach photos of vervose here shortly. forgot to mention i am also getting an appleALC failed to start. would having a third party battery cause issues?

**Comment by sikiro** [comment]
![691381D4-1943-4FA8-B126-73E49049FBD1](https://user-images.githubusercontent.com/9375953/61152155-a96c6580-a4b5-11e9-9b68-8dfe346e4848.jpeg)
![7865262C-3CA2-4F55-A9A3-B45EBC7C0B70](https://user-images.githubusercontent.com/9375953/61152156-a96c6580-a4b5-11e9-8281-b8811ddc1fd5.jpeg)


This is as far as it gets then I get the error I mentioned in post number 1
![F980844D-8D5A-4FE3-A4CE-03C6E9F81E5F](https://user-images.githubusercontent.com/9375953/61152639-fdc41500-a4b6-11e9-89c2-d3caf162f032.JPG)

**Comment by ameeno** [comment]
Is this pre installation?

**Comment by sikiro** [comment]
This is trying to do a fresh install yes

**Comment by ameeno** [comment]
Please try my previous commit before the kext update and let me know if
that works for you instead.

Unfortunately I do not have your CPU so cannot test on this end

**Comment by sikiro** [comment]
i have tried older commits unfortunately no luck i have also gotten some different config files from the osx forums and same issue even tho they have successfully installed it on the same hardware.

**Comment by sikiro** [comment]
![IMG_0034](https://user-images.githubusercontent.com/9375953/61161532-345b5900-a4d2-11e9-8404-02adc8d385df.jpg)
![IMG_0035](https://user-images.githubusercontent.com/9375953/61161533-345b5900-a4d2-11e9-9d56-f7fbc8dd90a0.jpg)
![IMG_0037](https://user-images.githubusercontent.com/9375953/61161534-345b5900-a4d2-11e9-88fc-e123c24ad231.jpg)
![IMG_0038](https://user-images.githubusercontent.com/9375953/61161535-345b5900-a4d2-11e9-94d6-b0fc8020bab5.jpg)
![IMG_0040](https://user-images.githubusercontent.com/9375953/61161536-345b5900-a4d2-11e9-8525-97c07bf8a576.jpg)
![IMG_0041](https://user-images.githubusercontent.com/9375953/61161538-34f3ef80-a4d2-11e9-880d-2111e28838c8.jpg)



maybe theres something in these images that can help.

**Comment by ameeno** [comment]
Recommend reset bios to default and boot via uefi only (no legacy boot)
cannot comment if it's faulty hardware

**Comment by sikiro** [comment]
have tried windows installs fine.

**Comment by ameeno** [comment]
Yes but is it gpt/ uefi? Do you know how to check?

Can you try usb?

Difficult to help when I cannot reproduce your issue.

**Comment by sikiro** [comment]
Are we talking about the format of the usb itself or the drive on the machine. I made an installer using the guide you provided on a windows machine both with a usb 2.0 drive and 3.0 the install I’ve done using uefi every attempt it’s weird I can’t even get to the installer.  

Edit:   made a usb installer on a mac using gpt. still same errors.

**Comment by sikiro** [comment]
it seems the issue is with the DSDT.aml if i run it without that i get a diferent result but it hangs at waiting for root device.

**Comment by ameeno** [comment]
ok try this in terms of your bios setup:

 Make sure you have BIOS set to Load Defaults, Apply it and then go back to set it to
UEFI
AHCI
Legacy Option ROMs Enabled
Secure Boot Disabled ﻿

Then use my boot pack, and then finally try:

next, try this boot pack attached 
[E7440_Mojave.zip](https://github.com/ameeno/Dell-E7440-Hackintosh/files/3390067/E7440_Mojave.zip)


Simply extract the zip file along with the ACPI & kext folders and overwrite the other folders on the USB.

Finally, make sure you have HFS and apfs loader in the drivers/UEFI folder, or it won't be able to see your drives. (This should already be inside my GitHub repo)

So 
0: make sure you set up your bios as instructed above.
1: Follow the guide to make USB
2: copy my github bootpack to your usb
3: use the boot pack in the zip to overwrite the relevant folders and config.plist to your zip folder

If you follow those steps in order, you should have no further problems.

Finally, this method requires that you have an ethernet cable attached during the macos Installation process.

**Comment by sikiro** [comment]
![IMG_0042](https://user-images.githubusercontent.com/9375953/61185806-62a07c00-a62b-11e9-9173-1ed2bf9259bc.jpg)
have followed all of your steps to the letter  running it with the included dsdt.aml file creates the same errors i showed in the screenshots above, however if i run it without it. my device detects the cpu but i get a IORESOURCE MATCH error followed by a kernel panic that says waiting for root device. does it matter that this machine is a touch 1080p display?. when running your dsdt or the one included above it gets unsuported cpu error as well.

**Comment by ameeno** [comment]
It may be to do with your bios revision or any number of things, and so you will most likely have to make custom patches to your dsdt for things like sound and screen and power management along the way specific to your machine.

Anywhoo try and use this dsdt to at least hopefully get you into the installer (the first step)

and boot mac OSx after install.


**WARNING** this may help you install/boot osx, but you will need to resort to your research/elsewhere to move beyond merely booting/installing to iron out all your system-specific bugs.

This has been tested on Bios A22 with i7 - 4600U.

Finally, if this does not work, look into bios downgrading (there is a setting in dell bios settings) as I know several CPU specific bug patches were rolled out by various manufacturers recently which may have gimped your system.

good luck!

[i7-4600U-E7440_A22.zip](https://github.com/ameeno/Dell-E7440-Hackintosh/files/3390193/i7-4600U-E7440_A22.zip)

(The AML is the compiled file you place in your EFI/ACPI/patched folder, the DSL is the disassembled file you can use as a base to apply sound and power patches in the future)

(I own 2x E7240's with 1080p touchscreen (i5) + 1x e7440 (currently 1366p, but used to be 1080p (i7) non touch screen. 
The e7240/7440 is virtually identical hardware and use the same bootpack.
So the dsdt is well tested)

**Comment by sikiro** [comment]
i believe you when you say its identical. i opened my device up again and it seeems cmos battery is missing that maybe causing issues. i tried downgrading and using this file and still no luck same results. ill wait for a cmos battery to come in the mail and try again. its the weirdest thing because it keeps saying unsuported cpu with your provided dsdt file.

**Comment by ameeno** [comment]
lol, you sure you don't have a third party, aftermarket, Chinese imitation
system with a fake CPU?

if you have access to another Mac machine, you can try and create a macOS
installer from that, and install clover onto the USB itself, and then use
the boot pack inside clover configurator on the mac.

that way you can install the latest macOS without having internet access,
so it will be easier to debug.

**Comment by sikiro** [comment]
i dont its a legit  device i have linux and windows on it on a sepreate drive. everything works fine lol. i made a full installer on a mac to try and still the same issue.

**Comment by sikiro** [comment]
wanted to thank you for trying to help me get this working unfortinately i have not found a solution. i checked to make sure my device was a legit one updated bios downgraded it. i have asked arround in other forums about what may be causing the issue and they say it may not be reading my usb drives. i purchased 6 diferent brands of usb drives usb 3 and 2.0 and it always gives me the same exact issue. its sad that i cant get it working i was looking forward to having a working hackintosh :(

**Comment by ameeno** [comment]
What drive are you using? Could you wipe and replace it?

**Comment by sikiro** [comment]
tried PNY 2.0 3.0 Sandisk 2.0 3.O  adata 2.0 and 3.0 as well. it seems that the device stops reading the usb at some point. during the process.  i have wiped replaced reinstalled on a mac on windows have done every step i could think of spent countless hours. trying. i am now trying something from hackintosh zone to see if itll boot.

**Comment by ameeno** [comment]
Try a full maxis install usb (need a Mac to create one) I think the netbook
usb is not working for you

**Comment by ameeno** [comment]
*full macos usb install

**Comment by sikiro** [comment]
so i have made a install disk using the Niresh hackintosh package and it boots and is installing. what i am going to do is install using that then clone the clover files and atempt to do a vanilla install with those files after see if that solves my issue. i think that my model is a tiny bit diferent than yours in the sense that my usb controller may actually difer from yous. so i may need genericachi kext for it.

**Comment by ameeno** [comment]
That sounds like you were not using ethernet cable and intel mausi kext on
your installer

**Comment by ameeno** [comment]
Yea could be usb layout buddy.

**Comment by sikiro** [comment]
so the hackintosh zone got me in but pc is set as a imac so need to play arround with tthat see if i can get it working.

**Comment by sikiro** [comment]
ive succesfully gott it to boot however i cannot get graphics to work properly no matter what i do. any ideas.?

**Comment by ameeno** [comment]
Use whatevergreen kext.

I think you should look again at your bios settings follow
previous instructions clearly

**Comment by sikiro** [comment]
already using whatever green it is detecting the card but it is showing a 7mb v memory. as i said everything is working great except that. i got this far using a diferent boot method but am using your kexts to have wifi and a few other things working i am also using the i7 dsdt and its detecting it as well.

**Comment by ameeno** [comment]
AHH so you need to do a dvmt patch for your system and basically replicate
the mods in the ddst

**Comment by sikiro** [comment]
do i need to have windows to do dvmt patch? can you point me in the right direction for those steps.

**Comment by ameeno** [comment]
https://osxlatitude.com/forums/topic/10549-how-to-change-dvmt-for-dell-system/

also, I recommend nosing around the forums so you can find a perhaps a
total fix for your particular issues.

**Comment by sikiro** [comment]
so graphics is related to eDP instead of the other option so i think im out of luck with my unit getting graphics to work :/

**Comment by ameeno** [comment]
Enable legacy booting in dell bios but still default boot via efi.

This should enable csm which is needed for Intel gfx to work

**Comment by Manolo742** [comment]
I must confess that with the same hardware configuration and the same EFI of his I have had all the same problems that Sikiro points out. The only solution for me was to try other EFI folders with which I could boot Catalina, but now I have problems with the USB ports.
