### ISSUE TITLE
the bluetooth doesn't work 

### ISSUE THREAD

**Issue by hongzhixiong** [ameeno/Dell-E7440-Hackintosh#2]
Hi,thanks for your configure, I also use the BCM94352, everything is OK, only the bluetooth doesn't work, I don't what's the problem. Do you know how to fix it? Thanks!

**Comment by tomichen** [comment]
Make sure that the model of device is BCM94352HMB, then, put relative kexts in the right place.
view details here: [link](https://github.com/toleda/wireless_half-mini)

**Comment by hongzhixiong** [comment]
> Make sure that the model of device is BCM94352HMB, then, put relative kexts in the right place.
> view details here: [link](https://github.com/toleda/wireless_half-mini)

Thanks, the bluetooth is done, but the sound (ALC292) not work. do you have the problem?

**Comment by ameeno** [comment]
The copy to LE folder will be updated today with the right Kexts for Bluetooth.
The sound should work with the current kext setups.

my advice makes sure you to a cold shutdown (Power of the system) and a cold reboot and see if sound works.

I am working to fix the static headphone issue where you receive static over headphones and will patch this when ready.

**Comment by tomichen** [comment]
Recently, I met a problem. The device would go to sleep when the laptop connected to the outside monitor by HDMI and closed the lid manually ？I have checked the box "prevent the computer from automatically sleeping when the monitor is turned off" in the energy saving option and used external power supply.

**Comment by ameeno** [comment]
I use amphetamine to prevent computer from going to sleep.

amphetamine is available on the app store for free.

You can set triggers for example 👍 
If laptop is connected to more than 1 display,
or for example, it is your home wifi,

or for example connected to home power.

Or any combination of the above.


here is my trigger settings in a screenshot for you.

I highly recommend amphetamine app to prevent sleep when sleep is not wanted!!!


Hope that helps!


![image](https://user-images.githubusercontent.com/388653/51128336-83744a00-181f-11e9-9d9a-d3b6b38012be.png)

**Comment by Largercode** [comment]
Thank you very much for sharing, I use a USB network card to solve the network problem, now it travels very well! I have a problem now and hope to get your help. There is no problem with the built-in speaker. When I plug in a 3.5mm headset (no microphone), the sound is converted to the headphones, but the noise is so loud that I can't hear the original sound.I am not sure if the USB card affects it.
