### ISSUE TITLE
 External speaker error

### ISSUE THREAD

**Issue by KaneGZ** [ameeno/Dell-E7440-Hackintosh#21]
I have installed macOS 10.14.6
Read carefully and follow the instructions, but it still has an external speaker error
My English is poor, can you help me?
Thank you!

**Comment by zavvod** [comment]
I have similar trouble and i cant solve this (

**Comment by ameeno** [comment]
please look in the audiofix folder for a script you must install afterwords, make sure that codec commander is installed.

**Comment by ameeno** [comment]
https://github.com/ameeno/Dell-E7440-Hackintosh/tree/master/Audio

**Comment by zavvod** [comment]
I fix this problem.
Unzip this archive
Open terminal 
Type cd(change directory) to current folder
Lounch fix script.
Profit.
