### ISSUE TITLE
WiFi Working Whit USB WiFi

### ISSUE THREAD

**Issue by RaimonxDev** [ameeno/Dell-E7440-Hackintosh#24]
Hi ameeno, I read your guide.  I am from Chile and I did not find this dw1550 card in my country, if I will buy and export to Chile this card will cost me $ 60, but I saw in free market and I found this USB link
https://www.tp-link.com/en/home-networking/adapter/archer-t600u-nano/
and the cost is $ 20.  My question is, can this USB work?  I see in are compatible with Mac. Awaited your response Thank you
PD: Sorry for my english :)

**Comment by ameeno** [comment]
Hi RaimonxDev,

I have tested and tried TPlink Wifi cards (USB) before.

I can confirm they do work and provide wireless to Mac.

But there is a few caveats.

1, TPLINK usb devices require special drivers to be installed, you can eaither download driver from internet via ethernet, or put on usb.

2. Tplink devices require special connection software and special connection using tplink wifi.

you cannot connect using apple wifi interface.


MacOS see;s the wifi card as an "External" or non-native wifi card, and treats it differently from apple hardware.

you cannot do airdrop or any of the other cool things you can with native wifi card.


Hackintosh compatible wifi cards spoof native apple wifi hardware.

hope that helps

**Comment by RaimonxDev** [comment]
oh!  Thanks for answering.  Well, the truth is that I don't have any Apple product, I just want to use the macOS environment to develop frontend studio and I would like to experiment!  for now I need to download some libraries js and working WordPress php etc, or watch videos of tutorials, YouTube, udemy is basically to develop, maybe in the future I bought the compatible WiFi card and change it

**Comment by RaimonxDev** [comment]
I have another Query! In the clover installation guide I don't know until what step I should arrive! I currently reached clover and friends part 1! and I don't know if I have to complete all the steps up to clover and friends part 2? or I just have to download the repository!

**Comment by ameeno** [comment]
That's another person's guide, please ask there.
