### ISSUE TITLE
Update from Mojave to Catalina

### ISSUE THREAD

**Issue by crbgx** [ameeno/Dell-E7440-Hackintosh#25]
Hi! I was wondering if updating through the normal system updater should cause any sort of issue. Has someone tried already? i have updated previously tiny updates and they all worked fine, but as this one is 8GBs big and we are changing macOS version to 10.15 i'm just not sure if it will work or not.

Thx for ur help in advanced

**Comment by ameeno** [comment]
Backup with time machine or another took to create a bootable image. Try upgrading, otherwise roll back if failed.

I have not tested catalina

**Comment by crbgx** [comment]
I tried updating, both with a clean install from a USB drive and also from the updater but neither will work.

No big deal really, Mojave works great on my Dell so I can only say thanks
