### ISSUE TITLE
Stuck on boot please help

### ISSUE THREAD

**Issue by eeeeeeelukeeeeeeee** [ameeno/Dell-E7440-Hackintosh#26]
This is my first hackintosh so I’ve tried my best to follow the instructions correctly and I think I have, I did everything as instructed but it gets stuck on the full apple bar, I’ve run it in this mode so you can see the code
![image](https://user-images.githubusercontent.com/56357950/66501701-70fd1780-eaf6-11e9-806b-cdd042cdc575.jpg)

**Comment by ameeno** [comment]
Why do you have both fakesmc and virtualsmc?

You cannot use both.

My boot pack uses just virtualsmc. I would recommend using a real mac to wipe a USB flash drive, and install clover onto the usb flash drive with my boot pack.

Use the usb flash drive to boot your hackintosh

**Comment by eeeeeeelukeeeeeeee** [comment]
I’m not sure I think it downloaded when I dragged the path in the cmd and it downloaded the clover(it came with some kexts I copied your kexts over it and only replaced the duplicates so there will be the original ones), I don’t have a real make to do that on, do you have a link that has simple instructions with maybe pictures to help me set up my efi?

**Comment by eeeeeeelukeeeeeeee** [comment]
If I use transmac to wipe the drive and load the dmg then use a partition tool to see the efi folder and then use explorer++ to alter my efi will it work? Also should I replace the whole efi folder with your repository or just add to the original?

**Comment by ameeno** [comment]
Yes but it's more complicated. Basically you need to clean up efi folder
kexts.

Experiment until it boosts m8, your boot files are wrong. Good luck m8

**Comment by eeeeeeelukeeeeeeee** [comment]
I used trans Mac then ran your guide it worked! Thank you got in then didn’t know how to follow your guide on the clover install and the ssd so I downloaded the clover  manually(took me around 3 hours to actually make it bootable as I have no idea what I’m doing haha) I’ve done everything but the audio because I don’t understand what “terminal: and run” inside the folder, I know how to get to the terminal but don’t know how to open the terminal while in folder, also my permission note is locked so I don’t understand how to clean and rebuild, getting there though thank you
