### ISSUE TITLE
3.5mm headset (no microphone) Very noisy

### ISSUE THREAD

**Issue by Largercode** [ameeno/Dell-E7440-Hackintosh#3]
Thank you very much for sharing, I use a USB network card to solve the network problem, now it travels very well! I have a problem now and hope to get your help. There is no problem with the built-in speaker. When I plug in a 3.5mm headset (no microphone), the sound is converted to the headphones, but the noise is so loud that I can't hear the original sound.I am not sure if the USB card affects it.

**Comment by Largercode** [comment]
Oh, I am negligent, I ran the license - E7440.sh. It is perfect now. Thank you! ! ! ! ! ! ! !

**Comment by ameeno** [comment]
sometimes there is this bug, there is a couple of fixes.

One thing to do is press F11 from CLover boot loader to clear EFI and it will be fixed until sleep/wake.

there is new patch coming soon which will solve this problem.

**Comment by ameeno** [comment]
There are some updates in the repository to fix the headphone output issue. use the alc_fix file and the updated kexts.
