### ISSUE TITLE
Dell Latitude E7440

### ISSUE THREAD

**Issue by Aldeab** [ameeno/Dell-E7440-Hackintosh#4]
hey 🙌
Is it possible to install hackintosh "’MacOS Mojave" on:
Dell Latitude E7440 Core i5 
8GB RAM. Storage: 250 SSD

Please note: I will install Xcode on it!
Will it work without any slowdown?
thanks 👍

**Comment by ameeno** [comment]
Yes

**Comment by Aldeab** [comment]
Hi

I have seen many explanations that confirm that it is possible to work with you Wi-Fi

Without having to use an external card!

I tried and did not work with me any way

Maybe the reason I did not do it right?

// Can you give me the right way to do it \

I desperately need your help, my friendMy device:

Dell LATITUDE

Core i-5 4th Gen

RAM 8 GB

256 GB SSD

btw I'm on High Sierra 10.13

**Comment by ameeno** [comment]
You *Cannot* and will *Never* be able to use built in dell WiFi card.

You *MUST* change and replace internal WiFi card to AW-CE123H wifi card.

To do this, you *MUST* open up laptop internally.

Take out old wifi card with a screw driver, and put in the new wifi card
AW-CE123H card.

You can buy this card from maybe ebay for Approximately 20USD.

This card is here details:
https://wikidevi.com/wiki/AzureWave_AW-CE123H
https://wikidevi.com/wiki/Broadcom_BCM94352HMB

this card has many names: AW-CE123H, Broadcom BCM94352HMB, BCM94352, Dell
Wireless DW1550, ACER 4352.

The size you MUST GET (if you do not want to lose your SSD SLOT) is HALF
SIZED MINI PCIE.


SO to summary, You must get Broadcom 4352 Mini Half sized PCIE card, and
Open Laptop and CHANGE wireless card to this card.

ANd then you can use my bootpack for perfect hackintosh.


If you want easy way without opening laptop, you can use simple tplink USB
wifi adapter and do not need any special stuff.

thanks.
