### ISSUE TITLE
Wifi not working

### ISSUE THREAD

**Issue by Rooster69** [ameeno/Dell-E7440-Hackintosh#5]
Hi,

I have followed the instruction and installed Mojove. Everything seems to be working but the Ethernet and WiFi.

Could you please help.

Tia

**Comment by ameeno** [comment]
Ethernet will work. WiFi will not work without the correct WiFi card I mentioned.

make sure you run the shell script (.sh) after installing kexts.

also reset nvram at the clover boot screen (press F1 and then f11) to clear the system memory. and then reboot.

**Comment by Rooster69** [comment]
Thank you.

**Comment by bozanbungee** [comment]
Hello 

> Ethernet will work. WiFi will not work without the correct WiFi card I mentioned.
> 
> make sure you run the shell script (.sh) after installing kexts.
> 
> also reset nvram at the clover boot screen (press F1 and then f11) to clear the system memory. and then reboot.



> Ethernet will work. WiFi will not work without the correct WiFi card I mentioned.
> 
> make sure you run the shell script (.sh) after installing kexts.
> 
> also reset nvram at the clover boot screen (press F1 and then f11) to clear the system memory. and then reboot.

Hello ameeno. Thank you about your nice work. I build one Hackintosh according your . Everything works perfect. Just WiFi. My card is Intel Dual Band Wireless-AC 7260 Model: 7260HMW. So my question: I have to buy the card you mentioned and I have to replace existing one ?

Thank you

**Comment by ameeno** [comment]
yes. Intel WiFi is not supported on any Mac's. Apple does not use these cards I. there own Macs. I have read some success with usb WiFi dongles (uplink) but my best experience is with the card I have mentioned.


best thing to do is to Google "hackintosh WiFi" to find a list of compatible WiFi cards. 

I am closing this issue, it is not an issue with the bootpack
