### ISSUE TITLE
update problems

### ISSUE THREAD

**Issue by tomichen** [ameeno/Dell-E7440-Hackintosh#6]
Hi, guys, recently I want to upgrade my laptop from 10.13.6 to 10.14.4. You know, big version upgrade may cause some unpredictable problems. In order to ensure the original data safe and smooth upgrade, I want to know whether manual upgrade could work (could not automatic upgrade from App store, only could download OS image) after replace all files in EFI folder base on this website. 
Manual upgrade guide : [link](https://support.apple.com/en-us/HT201475)

Any response will be greatly appreciated, Thanks！

**Comment by ameeno** [comment]
not related to this bootpack.


this pack is almost 100% vanilla so your hard drive is identical to a genuine Mac.


use backup software such as CCC or time machine before upgrading

**Comment by tomichen** [comment]
The hard drive is identical to a genuine Mac. You means this bootpack could be compatible with the new version 10.14.4 without no booting problems and Only what I need is backup software ?

**Comment by ameeno** [comment]
Yes. We put most of our boot critical modifications inside the EFI folder, which loads at boot time.

The Mac OS installation is identical to a real Mac without modification of the system.

So all our modifications are done at boot time via clover code injection.

You can try upgrading directly like myself and many other people successfully have. But you should backup first or install to a spare hard drive.
