### ISSUE TITLE
Camera did not work

### ISSUE THREAD

**Issue by tomichen** [ameeno/Dell-E7440-Hackintosh#7]
Hello, guys ! I have upgrade my laptop to latest version (macOS Mojave 10.14.4). Everything works fine except camera. The system could not detect it and I have checked the necessary files including kexts, so anyone could give some advices ?

**Comment by ameeno** [comment]
working here, make sure you run sthe script in EFI/E7440_Fixes/permission-E7440.sh also run the alc fix inside same folder. shut down pc after script not reboot. let me know if its working.

Camera is on the USB Bus so any camera problem is related to USB.

also,

make sure you check windows/linux for camera to see if camera itself is not faulty.

**Comment by tomichen** [comment]
I put USBInjectAll.kext into the EFI folder and it works. The method mentioned was of no use.

**Comment by ameeno** [comment]
Interesting.

Very Interesting.

Now to be clear, USBInjectALL kext is a kext designed for testing purposes and should be used as a basis to make your own patches.

So the Included USB kext in my bundle does not work for you?
( 	USBPorts_E7440.kext)
Perthaps you have a different (Slightly) USB bus layout than my kext covers.


Glad you got it sorted, but please make your own patch for your own system and send it to me, i can add it as an option.
