### ISSUE TITLE
When we need to run Dell-E7440-Hackintosh / EFI / CLOVER / E7440 Fixes / alc_fix_ALC292 / install.sh?

### ISSUE THREAD

**Issue by xiangtailiang** [ameeno/Dell-E7440-Hackintosh#8]
Hi ameeno，Thanks for your awesome job!

I saw you add the alc_fix_ALC292 floder, but not refer it in README.
So when we need to run Dell-E7440-Hackintosh / EFI / CLOVER / E7440 Fixes / alc_fix_ALC292 / install.sh?
Or it is not need to do?

Thank you.

**Comment by ameeno** [comment]
yes that is correct, after all things is done (kext efi ect)

boot into your Mac system, unzip the alc_fix somewhere, and run the install.sh as sudo.

hope that helps
