### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by rontlz** [ameeno/Dell-E7440-Hackintosh#9]
Hi I was wondering if you could have a Look at my log file to see why I can't install 
Mojave 10.14.5.02 on my E7440?
I have your EFI Folder in my EFI Partition of the installer USB.
It has Bios A25 and the suggested settings in the bios.

Regards,

Ron

[Installer Log 05-30-19.txt](https://github.com/ameeno/Dell-E7440-Hackintosh/files/3236602/Installer.Log.05-30-19.txt)

**Comment by ameeno** [comment]
> ageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=110 "An error occurred while extracting files from the package “Core.pkg”." UserInfo={PKInstallPackageSHA256Digest=6af2a023a4f2f56400cbcc6d1c2d2624227a2e301b8d767a4a085a260fd04fa0, NSLocalizedDescription=An error occurred while extracting files from the package “Core.pkg”., NSFilePath=/Volumes/Hackintosh/.OSInstallSandboxPath/Root, NSURL=Core.pkg -- file:///Volumes/InstallESD/Packages/OSInstall.mpkg, PKInstallPackageIdentifier=com.apple.pkg.Core, NSUnderlyingError=0x7fb242d7b410 {Error Domain=BOMCopierFatalError Code=1 "cpio read error: Undefined error: 0" UserInfo={NSLocalizedFailureReason=cpio read error: Undefined error: 0, offset=17688086, type=BOMCopierFatalError, sourcePath=/Volumes/InstallESD/Packages/Core.pkg, destinationPath=/Volumes/Hackintosh/.OSInstallSandboxPath/Root}}} {
	    NSFilePath = "/Volumes/Hackintosh/.OSInstallSandboxPath/Root";
	    NSLocalizedDescription = "An error occurred while extracting files from the package \U201cCore.pkg\U201d.";
	    NSURL = "Core.pkg -- file:///Volumes/InstallESD/Packages/OSInstall.mpkg";
	    NSUnderlyingError = "Error Domain=BOMCopierFatalError Code=1 \"cpio read error: Undefined error: 0\" UserInfo={NSLocalizedFailureReason=cpio read error: Undefined error: 0, offset=17688086, type=BOMCopierFatalError, sourcePath=/Volumes/InstallESD/Packages/Core.pkg, destinationPath=/Volumes/Hackintosh/.OSInstallSandboxPath/Root}";
	    PKInstallPackageIdentifier = "com.apple.pkg.Core";
	    PKInstallPackageSHA256Digest = 6af2a023a4f2f56400cbcc6d1c2d2624227a2e301b8d767a4a085a260fd04fa0;
	}
May 30 20:21:45 192-168-1-105 OSInstaller[577]: OSIInstallElement <OSIInstallElement: 0x7fb242c94260> errored out: Error Domain=PKInstallErrorDomain Code=110 "An error occurred installing macOS. To use Apple Diagnostics to check your Mac hardware, shut down, press the power button, and immediately hold the ‘D’ key until diagnostics begins." UserInfo={NSLocalizedDescription=An error occurred installing macOS. To use Apple Diagnostics to check your Mac hardware, shut down, press the power button, and immediately hold the ‘D’ key until diagnostics begins.}
May 30 20:21:45 192-168-1-105 OSInstaller[577]: Clearing automation and attempting to rebless. source volume: SKAPFSDisk { APFS UUID: 96B61F75-D35D-36AA-A263-E18DB81384AA, CONTAINER UUID: 384C3417-759E-47E2-B4EF-BD7CC761B673, DISK ID: disk22s1 ENCRYPTED: NO }  rebless: B27F1885-160A-3044-A391-97935B9D9247
May 30 20:21:45 192-168-1-105 storagekitd[578]: Ejecting 1 disks


> 


This section is indicating to me there is a problem with your core.pkg file in your installer being unable to extract.

Have you tried a different installer? With ethernet connected?

Perhaps make a full installer USB from another mac or another Hackintosh, to make sure you have a perfect install USB.

As it seems like a faulty USB/faulty install files.

Keep me, updated mate,

**Comment by rontlz** [comment]
Hi, thanks for looking at it so quickly, I made another usb installer on a different drive and copied your
EFI Folder on to it and it booted up the clover menu from the new usb and I chose to install it,
now it just runs through a bit of code and then it hangs at " creating RAM disk for /var/tmp/OSISPredicateUpdateProductTemp"
how would I get the log file for you at this point?

Kind Regards,
Ron

**Comment by ameeno** [comment]
In the clover boot screen, if you press F1, you will see various options to dump boot logs, screenshots and ram / Prepateched images to your EFI subfolders.

Additionally, you can press space on each boot item to change individual boot options to capture some logs.


Without much more information I still think it's your installer. How exactly are you making your install USB??


Do you have ethernet plugged in or wifi for the Mojave installer step?

**Comment by rontlz** [comment]
I have a real MacBook Pro that I downloaded the Mojave installer app through the update process
and saved it in my applications folder. I then formatted the usb with disk utility and then copied the
Mojave installer onto the usb with a terminal script I then copied your EFI Folder onto the EFI Partition
is this the correct way to do it?

**Comment by ameeno** [comment]
That should work and is one of the best ways to do it.

Step one (On your mbp with Mojave, with Mojave installer downloaded)
> sudo /Applications/Install\ macOS\ Mojave.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume
>

This will create a Mojave installer onto your USB drive.

Next, download and install Clover & Clover configurator.
 from
>
https://mackie100projects.altervista.org/download-clover-configurator/
&
https://sourceforge.net/projects/cloverefiboot/files/Installer/
>


finally, I would run the clover installer (Obtained from SourceForge) to install clover onto the Mojave installer USB.

Once the Installer USB is prepared with a naked clover, feel free to copy my EFI/CLOVER folder over your EFI/CLOVER folder and replace.



Please let me know if you make progress.

**Comment by ameeno** [comment]
also try:
 boot with boot arg

-igfxvesa

 

Repair permission and rebuild cache, reboot normally ﻿


also make sure  Replace contents into /EFI/Clover and try again

Make sure you have BIOS set to Load Defaults, Apply it and then go back to set it to

UEFI

AHCI

Legacy Option ROMs Enabled

Secure Boot Disabled 

(your bios settings)


 If you're using the files I linked, then make sure you copy the kexts inside /EFI/Clover/kexts/Other/CopytoLE to /Library/Extensions

Repair permissions and rebuild cache

      sudo chmod -Rf 755 /L*/E*

      sudo chown -Rf 0:0 /L*/E*

      sudo touch -f /L*/E*

      sudo chmod -Rf 755 /S*/L*/E*

      sudo chown -Rf 0:0 /S*/L*/E*

      sudo touch -f /S*/L*/E*

      sudo kextcache -Boot -U /﻿

 

Wifi, I assume you have Intel if it's not working. Intel wifi is not supported and must be replaced with a supported device.

**Comment by rontlz** [comment]
when I run the clover installer, do I need to choose any of the install options, I did choose my usb as the install location but there are a lot of other options under customise

**Comment by rontlz** [comment]
also do I do the kext copy and repair and rebuild commands after I get it all working?
I swapped out the intel wifi adapter

**Comment by ameeno** [comment]
Choose for UEFI Booting Only, Disable "install clover preference pane".

the destination is your USB.


Once we install the clover, you can either replace the entire clover folder with mine; it might be better if you replace the ACPI folder kext Folder Driversuefi64 folders and place my config.plist into the root of the CLOVER folder.

the result will be, you will have the very latest clover installation on your USB, and the very latest Mojave on your USB, but my customisations will also be present.

**Comment by rontlz** [comment]
Ok I downloaded a fresh copy of Mojave via ethernet on my mbp
I erased a new usb, I installed Mojave onto the usb with your script.
I installed clover Bootloader and copied over your suggested files and folders.
I reset the bios to defaults saved and changed the suggested settings.
I got to the same spot and it failed, I don't know what is going on.
Log file attached, any ideas?

Regards,
Ron
[Installer Log 05-31-19.txt](https://github.com/ameeno/Dell-E7440-Hackintosh/files/3239561/Installer.Log.05-31-19.txt)

**Comment by ameeno** [comment]
please share your hardware setup

(WiFi card hard drives ram ect) 

your complete bios setup.

do you have any other operating systems on your PC right now? what is your current system partition layout? 

is your main drive gpt format?

**Comment by rontlz** [comment]
Ok will try that tomorrow now
Late here, thank you for your help


Regards,

Ron

**Comment by rontlz** [comment]
Standard Dell E7440 except i took out the Intel wi-fi card and installed a AR5B95.
128gb M.2 Sata ssd hard drive, 2 x 8gb dimms, usb mouse plugged in to rear port.
no operating system installed on the hard drive except a failed mojave.
i have tried at least 10 times and each time i erase the internal hard drive with disk utility.
BIOS is A25 and has been set to default many times, changed hd mode to ahci and uefi
disabled secure boot turned on legacy option roms (i get weird graphics if off)
I just thought of something i can try, i will do a memory test on my ram in case one is faulty.
I was running windows 10 ok before trying to do the hack.

**Comment by ameeno** [comment]
Ok, thanks for that.

No re your wifi card, Not sure it's compatible, and my boot pack does not contain any specific Kexts for this card.

Now, the Atheros cards used to work, but Apple removed support for Atheros in Mojave.

There is a workaround which I have used in the past.

this dude has an app called Mojave patcher, which patches your Mojave installer:
http://dosdude1.com/mojave/

it is designed for real macs loading newer versions on older machines, but it can be used using the wifi patcher (Though I would invest in a new card)

before you patch the install, how about trying to remove the Atheros ethernet card, and running through an install without any wifi card present?

Also, there is a possibility (small) that your partition table on your SSD is a bit faulty,

the only way around that would be to create a new partition table (AS GPT) using gparted inside a live Linux environment.

I think it's unlikely to be this, as wiping via disk utility should achieve the same thing.

Also, sure do a ram test from the dell bios setup utility, make sure there is no faulty ram.

I would use disk utility to make a partition like this:
1 - In dis utility Erase drive, & add an HFS partition spanning the whole disk (Apple journaled format),
2: SPlit your newly created hfs partition into two partitions of equal sizes (This creates an EFI partition automatically)
3rd, I would reformat the first partition into exFAT format (so it is readable by windows)
4th, I would run a windows installer using the boot USB, and while installing windows 10, I would select the first partition (that's readable) and install windows there. Windows will automatically format this to NTFS.

Once you have working windows install, proceed to install macOS (Selecting the second partition in apple installer)

this will reformat your 2nd partition into APFS, the EFI will be shared between all operating systems.


Really, based on your configuration, apart from the wifi card/a dirty partition table on your SSD/faulty hardware, i cannot see how it would not work.

I hope this helps!

**Comment by ameeno** [comment]
Ron: One thing i wanted to add is:

If using the dosdude1 Mojave patcher on to make your USB installer, Install CLOVER to the USB after you have created the usb installer.

And move my EFI onto the usb after that. this way, you start the first part of the installer booting via clover, and then use the post install feature in the patcher to patch up your wifi card and other patches you think you could need.


Good Luck!

**Comment by rontlz** [comment]
Ok i will remove the AR5B95 card and purchase the BCM card
i will do the ram test and try an install without any wifi card if the ram is ok.

**Comment by rontlz** [comment]
Ok I tested all the hardware through the Dell PSA, all good.
I removed the AR5B95 and tried the install windows first method you described.
Windows 10 installed ok, and the Mojave installed ok to the second partition!
Everything on the Hackintosh working great straight out of the box so to speak,
did all the post install stuff and rebooted, now I can only get windows option in the clover
boot menu, how do I add my Mac OS back into the boot list under clover?
Or should I just do another clean Mojave install on the whole hard drive now?

**Comment by ameeno** [comment]
Ok.

Great stuff.

easiest way: use your clover install usb to boot your hackintosh, and then install clover onto Mac hard drive using the clover install PKG once inside Mac.


copy the efi clover folder from mine to your efi (on clover hard drive)

second way is a bit more complicated but involves hand editing the efi boot table from Windows using bcdedit (not recommended unless you knew what you where doing)


if you have erased your clover boot usb, you can make a new one. there is my guide telling you how to make boot usb from Windows.


good luck

**Comment by ameeno** [comment]
AHH just re read your problem. you see clover but not your Mac boot options?


well that will perhaps be a issue with drivers or your config.plist. 

can you check your clover folder inside your efi  clover folder to make sure you have everything there? particularly if your missing hfs or apfsdriverloader?

these drivers are responsible for detecting and loading theac partition.
